name: CI

on:
  push:
    branches:
      - main
  

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          
          pip install -r microservices/service1/requirements.txt
          pip install -r microservices/service2/requirements.txt
          pip install flake8 pytest

      - name: Run flake8
        run: flake8 microservices

      - name: Run tests
        run: |
          pytest microservices/service1/tests
          pytest microservices/service2/tests
